<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="style.css">
    <title>User</title>
</head>
<body>
    <form method="post" action="create_user.php">
        <dl>
            <div>
                <dt>Nom</dt>
                <dd><input id="ensemble" type="text" name="firstname"></dd>
            </div>

            <div>
                <dt>Prénom</dt>
                <dd><input id="ensemble" type="text" name="lastname"></dd>
            </div>

            <div>
                <dt>Email</dt>
                <dd><input id="mail" type="email" name="email"></dd>
            </div>

            <div>
                <dt> Mot de passe</dt>
                <dd><input id="password" type="password" name="password"></dd>
            </div>
        </dl>
        <div class="submit">
            <input id="button" type="submit"  name="button" value="Enregistrer">
        </div>
    </form>
</body>
</html>

